# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
    tags:
      - '!v*'
  pull_request:
    branches:
      - '**'
    tags:
      - '!v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: npm test
